version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
      - DB_NAME=rick_and_morty_db
      - JWT_SECRET=your_secret_key
  db:
    image: postgres
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=rick_and_morty_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: